### ISSUE TITLE
Create a models.py

### ISSUE THREAD

**Issue by hjcho7311** [NYU-DevOps-Spring2018-Orders/orders#2]
**As a** ...  developer
**I need** ...  order model
**So that** ...  our model can hold  definitions of our resource.

**Assumptions:**
1. Order id
2. Customer id
3. Product id
4. Product qty
5. Price
6. Order status

**Acceptance Criteria:**
```
Given the inputs above, the model should be instantiated without any errors
```

**Comment by hjcho7311** [comment]
@ericderegt I guess you have a reason to have separate "api" and "models" structure.

**Comment by ericderegt** [comment]
Mainly just to have a [separation of concerns](https://en.wikipedia.org/wiki/Separation_of_concerns). A module should have one thing it does well. Since we have two models now instead of the one in the Pets example, we should have separate pieces of code for the orders and items. This makes it easier to reason about what each file is responsible for rather than just putting all of the models together.
